"""
Streamlit UI for the RAG Ticket Intelligence System.

Talks to the Flask API running on localhost:5000.
Start the API first:  python src/api.py
Then run this:        streamlit run streamlit_app.py
"""

import streamlit as st
import requests

API_URL = "http://localhost:5001"

# ── Page config ───────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="IT Ticket Intelligence",
    page_icon="🎫",
    layout="wide",
)

st.title("🎫 IT Ticket Intelligence")
st.caption("Enter a ticket description to get an automated classification and resolution suggestion.")

# ── Input ─────────────────────────────────────────────────────────────────────

description = st.text_area(
    "Ticket description",
    height=150,
    placeholder="e.g. My VPN keeps disconnecting every 10 minutes and I can't stay connected to internal resources...",
)

analyse = st.button("Analyse Ticket", type="primary", disabled=not description.strip())

# ── Output ────────────────────────────────────────────────────────────────────

if analyse and description.strip():

    col1, col2 = st.columns([1, 2])

    # ── Classification ────────────────────────────────────────────────────────
    with col1:
        st.subheader("Classification")

        with st.spinner("Classifying..."):
            try:
                r = requests.post(
                    f"{API_URL}/classify",
                    json={"description": description},
                    timeout=30,
                )
                r.raise_for_status()
                clf = r.json()
            except requests.exceptions.ConnectionError:
                st.error("Cannot connect to the API. Make sure `python src/api.py` is running.")
                st.stop()
            except Exception as e:
                st.error(f"Classification failed: {e}")
                st.stop()

        # Priority badge colour
        priority_colours = {
            "Critical": "🔴",
            "High":     "🟠",
            "Medium":   "🟡",
            "Low":      "🟢",
        }
        badge = priority_colours.get(clf["priority"], "⚪")

        st.metric("Category", clf["category"])
        st.metric("Priority", f"{badge} {clf['priority']}")

        st.caption(f"Category confidence: {clf['category_confidence']:.0%}")
        st.caption(f"Priority confidence: {clf['priority_confidence']:.0%}")

        # Show full probability distributions in an expander
        with st.expander("All scores"):
            st.write("**Category**")
            sorted_cat = sorted(clf["category_scores"].items(), key=lambda x: -x[1])
            for label, score in sorted_cat:
                st.progress(score, text=f"{label}: {score:.0%}")

            st.write("**Priority**")
            for label in ["Critical", "High", "Medium", "Low"]:
                score = clf["priority_scores"].get(label, 0)
                st.progress(score, text=f"{label}: {score:.0%}")

    # ── Resolution ────────────────────────────────────────────────────────────
    with col2:
        st.subheader("Resolution Suggestion")
        st.caption("Generated by Mistral 7B via Ollama, grounded in similar resolved tickets.")

        with st.spinner("Generating resolution (this takes 10–30s)..."):
            try:
                r = requests.post(
                    f"{API_URL}/resolve",
                    json={"description": description},
                    timeout=120,
                )
                r.raise_for_status()
                rag = r.json()
            except Exception as e:
                st.error(f"Resolution failed: {e}")
                st.stop()

        st.markdown(rag["response"])

        # ── Sources ───────────────────────────────────────────────────────────
        st.subheader("Sources used as context")
        st.caption("Top 5 similar resolved tickets retrieved from the knowledge base.")

        for i, src in enumerate(rag["sources"], 1):
            with st.expander(f"{i}. [{src['category']}] {src['subject']}  —  {src['priority']} priority"):
                st.write(f"**Resolution:** {src['resolution']}")
                st.caption(f"Relevance score: {src['rerank_score']:.3f}")
